export const POST_SETTLE_REVEAL_ABI = [
  "function nextSwapId() view returns (uint256)",
  "function getSwapIntent(uint256 swapId) view returns (address trader, bytes32 poolId, uint256 nonce, uint256 createdAtBlock, uint8 state)",
  "function getSettlementRecord(uint256 swapId) view returns (uint256 recordSwapId, int128 delta0, int128 delta1, int256 amountSpecified, uint256 settledAtBlock, uint256 decryptReadyBlock)",
  "function revealSwapDetails(uint256 swapId)",
  "function setAuthorizedRevealer(address revealer, bool isAuthorized)",
  "function cancelStuckSwap(uint256 swapId)",
  "function autoReleaseStuckSwap(uint256 swapId)",
  "function cancelStuckAuction(uint256 swapId)",
  "function publishDecryptResult(bytes32 ctHash, uint128 decryptedValue, bytes signature)",
  "function CANCEL_DELAY_BLOCKS() view returns (uint256)",
  "function FALLBACK_DELAY_BLOCKS() view returns (uint256)",
  "function AUCTION_TIMEOUT_BLOCKS() view returns (uint256)",
  "function setEmergencyDelays(uint256 cancelBlocks, uint256 fallbackBlocks, uint256 auctionBlocks)",
  "event IntentCaptured(uint256 indexed swapId, address indexed trader, bytes32 indexed poolId, uint256 nonce, uint256 createdAtBlock)",
  "event SettlementRecorded(uint256 indexed swapId, address indexed trader, int128 delta0, int128 delta1, int256 amountSpecified, uint256 settledAtBlock)",
  "event RevealReady(uint256 indexed swapId, address indexed trader, uint256 decryptReadyBlock)",
  "event Revealed(uint256 indexed swapId, address indexed caller, address indexed trader, int128 delta0, int128 delta1, int256 amountSpecified, uint256 settledAtBlock)",
  "event SwapEmergencyResolved(uint256 indexed swapId, address indexed caller, string reason)",
  "event AuctionCancelled(uint256 indexed swapId, address indexed caller)",
  "event DecryptResultPublished(bytes32 indexed ctHash, uint128 decryptedValue)",
  // Custom errors — needed so reverts (incl. those bubbled through the swap router) decode by name.
  "error Unauthorized(address caller)",
  "error InvalidState(uint256 swapId, uint8 expected, uint8 actual)",
  "error NonceUsed(address trader, uint256 nonce)",
  "error RevealNotReady(uint256 swapId, uint256 readyBlock, uint256 currentBlock)",
  "error AlreadyRevealed(uint256 swapId)",
  "error MissingIntent(address trader)",
  "error PendingIntentExists(address trader, uint256 swapId)",
  "error InvalidHookData()",
  "error ExpiredIntent(uint256 deadline, uint256 currentTimestamp)",
  "error InvalidIntentSignature(address recovered, address expectedTrader)",
  "error SlippageCheckPending(uint256 swapId)",
  "error FillBelowEncryptedMinimum(uint256 swapId, uint128 actualAmountOut, uint128 minimumAmountOut)",
  "error DuplicateSolverBid(uint256 swapId, address solver)",
  "error SolverAuctionNoBids(uint256 swapId)",
  "error SolverAuctionAlreadyQueued(uint256 swapId)",
  "error SolverAuctionNotQueued(uint256 swapId)",
  "error SolverAuctionPending(uint256 swapId)",
  "error SolverAuctionAlreadyFinalized(uint256 swapId)",
  "error SolverAuctionWinnerNotFound(uint256 swapId)",
  "error SolverAuctionClosed(uint256 swapId, uint8 state)",
  "error CancelDelayNotElapsed(uint256 swapId, uint256 readyBlock, uint256 currentBlock)",
  "error FallbackDelayNotElapsed(uint256 swapId, uint256 readyBlock, uint256 currentBlock)",
  "error AuctionTimeoutNotElapsed(uint256 swapId, uint256 timeoutBlock, uint256 currentBlock)",
  "error SwapAlreadyEmergencyResolved(uint256 swapId)",
  "error InvalidEmergencyState(uint256 swapId, uint8 state)",
  "error InvalidCoFHESignature(address recovered, address expected)",
  "error AuctionAlreadyCancelled(uint256 swapId)",
];
